name: BoutiqueGEO
options:
  bundleIdPrefix: com.boutiquegeo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2"
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  BoutiqueGEO:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: BoutiqueGEO
        type: group
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boutiquegeo.app
        INFOPLIST_KEY_CFBundleDisplayName: "Boutique GEO"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UIStatusBarStyle: ""
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.business"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
